### ISSUE TITLE
experiment_tabular_cancer_dataset.ipynb

### ISSUE THREAD

**Issue by aly-bahaa** [x-y-zhao/BayLime#4]
I am trying to run the file experiment_tabular_cancer_dataset.ipynb, when i use model_regressor='Bay_info_prior' or 'non_Bay' or 'Bay_non_info_prior' i get the same error  '**str' object has no attribute 'fit'** , hope you can help me :)

Thanks in advance.

**Comment by x-y-zhao** [comment]
Hi Aly, with the limited information you give, I am not sure what exactly is happening. I suspect it could be a version issue (I was using Python version 3.7.3, scikit-learn version 0.22.1, Tensorflow version 2.0.0) or some files could not be loaded (please pay attention to the folder structure). May I suggest you debug it a bit and see where goes wrong, then I may help a bit.

As a side note, we are thinking to optimise the source code of BayLIME a bit to make it more version-compatible and easier to use.

**Comment by aly-bahaa** [comment]
> 

Do you recommend i downgrade my versions to the versions you used in order to run the **[BayLIME_tutorial_images.ipynb]** file or the **experiment_tabular_cancer_dataset.ipynb** ??( mine are python 3.9.12 , Tensorflow 2.8 and scikit-learn 1.0.2)

**Comment by x-y-zhao** [comment]
Please try 0.22.1 version of scikit-learn?

**Comment by aly-bahaa** [comment]
> Please try 0.22.1 version of scikit-learn?

This was the problem , it worked when i used 0.22.1 
Thank you !

**Comment by ymxl85** [comment]
hello ! I used 0.22.1 but it still report error
![Screenshot from 2023-09-08 17-46-11](https://github.com/x-y-zhao/BayLime/assets/59185220/d80fdb95-9cfd-42ad-a080-a548866d6096)
